version: "3"
services:
  db:
    container_name: postgres
    image: postgres:latest
    env_file: db.conf
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  db_volume: