---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Install pip
      yum: name=python-pip state=present
      become: yes
      become_method: sudo

    - name: Install docker-compose
      pip: name=docker-compose
      become: yes
      become_method: sudo

    - name: Deploy the project running on docker-compose.yml
      docker_service:
        project_src: /home/ec2-user/ormuco_challenge/
      become: yes
      become_method: sudo